# Generated by Django 4.0.4 on 2022-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('edad', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField(max_length=11, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
