# Generated by Django 4.0.4 on 2022-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0002_person_delete_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='camada',
        ),
    ]
