# Generated by Django 4.0.4 on 2022-05-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0004_estudiante_profesor_remove_persona_edad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Curso',
        ),
    ]
